### ISSUE TITLE
Proper install matlab-src functions

### ISSUE THREAD

**Issue by francesco-romano** [robotology/mex-wholebodymodel#20]
Matlab functions should be copied into the install folder.

(Let's say that in general everything that should be used should stay in the install folder and not in the build)

**Comment by francesco-romano** [comment]
ping

**Comment by DanielePucci** [comment]
ping

**Comment by traversaro** [comment]
Once a proper installation strategy is decided, it would be possible also to remove all the `addpath` hardcoded in the scripts [1], ref #17 .

[1] : https://github.com/orgs/robotology/teams/codyco-developers

**Comment by traversaro** [comment]
@naveenoid any updates?

**Comment by DanielePucci** [comment]
It's been six months that this issue has been open. Any updates?

**Comment by DanielePucci** [comment]
:+1:
