### ISSUE TITLE
Move repository to robotology

### ISSUE THREAD

**Issue by drdanz** [robotology/mex-wholebodymodel#23]
As discussed with @traversaro, this repository should be moved to [robotology](https://github.com/robotology)

cc-issue: robotology/robotology.github.io#2

**Comment by naveenoid** [comment]
Could you advise me on how to proceed?

**Comment by drdanz** [comment]
We just have to synchronise, come talk to me whenever you are ready for the move.

**Comment by drdanz** [comment]
Done

cc-issue: robotology/robotology.github.io#2
