### ISSUE TITLE
Simplified initialization mode

### ISSUE THREAD

**Issue by traversaro** [robotology/mex-wholebodymodel#33]
It would be nice to be able to initialize the `mex-wholebodymodel` by:
* passing directly a path to an urdf file to load the interface (in this case, all the joints of the model would be automatically added). 
* passing directly a path to an urdf file and a list of joints to use 
This would drastically simplify its use for new user/new robots.

Currently for adding a new robot to the mex-wholebodymodel you have to properly create a set of configuration files and copy/install it in a way that can be found by the Yarp ResourceFinder, an impossible task for a newbie.

**Comment by francesco-romano** [comment]
plus the fact that the whole configuration file is not needed for the model...

**Comment by DanielePucci** [comment]
:+1

**Comment by iron76** [comment]
:+1:
