### ISSUE TITLE
Unused initial g in both test scripts

### ISSUE THREAD

**Issue by Ganimed** [robotology/mex-wholebodymodel#34]
Hi all,

in both testing scripts "forwardDynamicsConsistencyTest.m" and "integrateForwardDynamics.m" there is an initial gravity vector created for the control torques with,

   gInit = wbm_generalisedBiasForces(R_b,p_b,params.qjInit,zeros(25,1),zeros(6,1));

but will never used. For the time-dependent parameter tau it will be used the zeros-function instead of gInit. Is zeros in this case just an initial dummy?
I've found this also in the forwardDynamics function at line 54. Internally g will be calculated but afterwards it will never used or returned.
Can somebody explain me what was the intention, the thought, to calculate there at these places "g" and "gInit"?
Thanks.

**Comment by traversaro** [comment]
I guess @naveenoid is the author of the script, so he is the right person to reply!

**Comment by Ganimed** [comment]
Ok, I will do that. Thanks.

**Comment by traversaro** [comment]
Feel free to update this issue, so everybody can get this info!

**Comment by Ganimed** [comment]
I will do that, as when I've got the information.

By the way, in the folder matlab-src there is the folder "worker_functions" where inside are some nice functions for general purposes. In my opinion it is more meaningful if the folder "worker_functions" is renamed into "toolbox". Then everybody understand what is inside.

**Comment by traversaro** [comment]
"toolbox" is a bit overloaded in matlab contexts. I would personally prefer something like "utils".

**Comment by Ganimed** [comment]
I understand. "utils" is also a good option. We will see ...

**Comment by Ganimed** [comment]
"utilities" or just "tools" is also an option ...

**Comment by naveenoid** [comment]
Is this still a problem? I thought it was discussed in detail in person? The gInit was used in one of the simulations to set the torque compensating gravity. Im closing this issue for now since we have an overload of others.

**Comment by Ganimed** [comment]
It was still confusing me, but now I understand. So you used it just temporarily for another simulation. Thanks for the info.

**Comment by traversaro** [comment]
For the kinematic testing cleanup that I am doing for solving https://github.com/robotology/mex-wholebodymodel/issues/30 , I remove the unused vector `gInit`.
