### ISSUE TITLE
Don't keep `.mat` files in the repo

### ISSUE THREAD

**Issue by traversaro** [robotology/mex-wholebodymodel#41]
I think that it makes sense to remove all the `.mat` files from the repo. 

 `.mat` files are binaries for which it is quite difficult to track the modifications, for example while checking the repo history. 

I think that all the `.mat` committed files can be replaced by `.m` files produced by [Simulink.saveVars](http://it.mathworks.com/help/simulink/slref/simulink.savevars.html) function. We will lose some precision in the stored results, but the overall benefit seems clear to me.

**Comment by naveenoid** [comment]
The only reason for this was the old issue regarding jointLimits. If that is fixed. it can be removed.

**Comment by traversaro** [comment]
For the same reason we don't need to have `.fig` files in the repo. @gabrielenava

**Comment by gabrielenava** [comment]
ok, capito

**Comment by traversaro** [comment]
:+1:

**Comment by gabrielenava** [comment]
all the .mat and .fig files have been eliminated and are not necessary anymore, so I think we can close this issue
