### ISSUE TITLE
[Interface] Remove wbm_setWorldLink ? 

### ISSUE THREAD

**Issue by traversaro** [robotology/mex-wholebodymodel#43]
A lot of users have been confused by the semantics of the `setWorldLink` function https://github.com/robotology/mex-wholebodymodel/issues/26 and now it is possible to use all the functions by directly passing the complete state https://github.com/robotology/mex-wholebodymodel/issues/27 . 

If no code it is supposed to use this function, perhaps it is a better idea to just remove it from the interface, to avoid confusion/misuse by the users? 

After that, for symmetry with all existing calls, it could make sense to have an updateState in which you pass all the state, with also the base position (basically a combination of setWorldFrame + updateState ). 

In this way we would be more consistent with all the existing interfaces.

**Comment by traversaro** [comment]
cc @naveenoid @gabrielenava  opinions?

**Comment by traversaro** [comment]
This would also have the side benefits of removing the hardcoded "l_sole" in the code ( https://github.com/robotology/mex-wholebodymodel/blob/6603ab444e828f05bcb71c0317e4421e97736ac8/src/modelstate.cpp#L41 ),

**Comment by traversaro** [comment]
Another example of confusion regarding `wbm_setWorldLink` semantics : https://github.com/robotology/mex-wholebodymodel/issues/47#issuecomment-150511583 .

**Comment by DanielePucci** [comment]
I completely agree with you: passing the whole state is the right way to go. How do we pass this state for  SE(3)" Do we pass quaternions or what? @naveenoid  opinions?

**Comment by traversaro** [comment]
We are currently passing rotation matrices.

**Comment by DanielePucci** [comment]
Now we are talking [1]

[1]: http://www.youtube.com/watch?v=k17KH6F63aE&t=1m24s

**Comment by naveenoid** [comment]
I will most likely remove this once PR https://github.com/robotology/mex-wholebodymodel/pull/49 is merged

**Comment by naveenoid** [comment]
Tackled in ttps://github.com/robotology/mex-wholebodymodel/pull/52
