### ISSUE TITLE
Avoid having different matlab files with the same name

### ISSUE THREAD

**Issue by traversaro** [robotology/mex-wholebodymodel#45]
This is necessary because a random user could just add to the path all the directories in mex-wholebodymodel recursivly, and thus there would be in ambiguity on which function/script it is called, that could cause hideous bugs (ask to @claudia-lat). 

*I repeat*: **NEVER EVER EVER** [1] *use the same name for two different matlab files, even if they are in two different folders.* 

Examples of duplicates files (tick when solved): 
 * [x] `forwardDynamics.m` (this is one is tragic because the different versions have totally different semantic meaning)
 * [x] `integrateForwardDynamics.m` 
 * [x] `forwardDynamics_zeroExternalForces.m`

[1] : https://youtu.be/o7MF-FHra4o?t=2m21s

**Comment by naveenoid** [comment]
capito! this came because of multiple developments on top of my original
forwardDynamics. Addressing soon.

**Comment by traversaro** [comment]
Actually the one in the root is just an outdated version, the real version of `forwardDynamics_zeroExternalForce` is of https://github.com/robotology/mex-wholebodymodel/blob/master/forwardDynamics_zeroExternalForces.m . 
In any case, both version should just be calls of forwardDynamics with zero input torques and null constraint list, see https://github.com/robotology/mex-wholebodymodel/issues/42 .

**Comment by DanielePucci** [comment]
I think that sometimes having the same name for different files may make sense. For instance, in 
~~~
https://github.com/robotology-playground/WBI-Toolbox-controllers/tree/master/controllers/torqueBalancing
~~~
we use several matlab files called
~~~
gains.m
~~~
associated with each robot, which contains the gains for the torqueBalancing. This is reminiscent of what we do with the torqueBalancing.c++. Opinions?

**Comment by traversaro** [comment]
Agreed [1], mostly because those are more configuration file in matlab syntax than actual scripts.

There are also other situations where it may be convenient to have two function with the same signature/name, in that case I think they should be placed in different packages. 

[1] :+1: (Perhaps **NEVER EVER EVER** can become **NEVER EVER SOMETIMES** :D ).

**Comment by naveenoid** [comment]
Isnt this addressed in https://github.com/robotology/mex-wholebodymodel/pull/49?

**Comment by traversaro** [comment]
Not all of them, there are still three forwardDynamics, two integrateForwardDynamics, etc etc.

**Comment by gabrielenava** [comment]
fixed in branch feature/torques_linear
