### ISSUE TITLE
Set initial floating base state

### ISSUE THREAD

**Issue by naveenoid** [robotology/mex-wholebodymodel#51]
As discussed with @traversaro having a function like wbm_setInitialFloatingBaseState accepting qj and a reference link might eliminate https://github.com/robotology/mex-wholebodymodel/issues/43 and solve issues brought on by https://github.com/robotology/mex-wholebodymodel/issues/47

I will go for a full matlab implementation once other things in the PR are fixed.

**Comment by naveenoid** [comment]
https://github.com/robotology/mex-wholebodymodel/pull/52

**Comment by traversaro** [comment]
Fixed in https://github.com/robotology/mex-wholebodymodel/pull/52 .
