### ISSUE TITLE
Deprecated files still in the release directory "mex-wholebodymodel"

### ISSUE THREAD

**Issue by Ganimed** [robotology/mex-wholebodymodel#56]
Hi guys,

I've seen in the master branch that there are still some files which I know that they are deprecated or experimental. So they should be deleted or moved to another place.

* Under _matlab/utilities_:
 * stldemo.m
 * stlread.m
 * quat2rot.m

 Maybe they should be moved into a folder outside of the release directory "mex-wholebodymodel". For example in "matlab-src/experimental".

* And under _matlab/wrappers_, there is still the file **wbm_setWorldLink.m** which will be never used again.

**Comment by naveenoid** [comment]
:+1:  Addressing in the next commit.
