### ISSUE TITLE
Document from where the formula in quaternionDerivative comes from

### ISSUE THREAD

**Issue by traversaro** [robotology/mex-wholebodymodel#59]
@DanielePucci I searched it (quickly) in 
https://www-sop.inria.fr/act_recherche/formulaire/uploads/phd-425.pdf but I could not find it.

**Comment by DanielePucci** [comment]
Page 101.

**Comment by traversaro** [comment]
Fixed in https://github.com/robotology/mex-wholebodymodel/blob/master/mex-wholebodymodel/matlab/utilities/quaternionDerivative.m .
