### ISSUE TITLE
Cmake: check dependencies

### ISSUE THREAD

**Issue by francesco-romano** [robotology/mex-wholebodymodel#67]
There are a lot of dependencies required by this project.
I think that a lot of these are not required (neither now, nor when the project was first created).

The CMakeLists.txt should then be cleaned.

**Comment by gabrielenava** [comment]
I deleted one not required dependency (paramHelp) that caused a cmake error while compiling codyco-superbuild.

**Comment by gabrielenava** [comment]
I tried to rewrite the CMakeLists.txt eliminating the unnecessary code, but I have no idea if dependencies are really necessary or not. this is the updateted [CMakeLists.txt](https://github.com/robotology/mex-wholebodymodel/blob/master/CMakeLists.txt)

**Comment by gabrielenava** [comment]
With the help of @Ganimed, I removed all unnecessary dependencies from CMakeLists so we can close this issue (see 45f8118c58497cb2b28b76f111e37b20b081823b and c882bf4ad74778abcfd44ac1d271864977366b68)
