### ISSUE TITLE
Unused wbm_setWorldLink.m function

### ISSUE THREAD

**Issue by traversaro** [robotology/mex-wholebodymodel#74]
I think `wbm_setWorldLink` is unused since https://github.com/robotology/mex-wholebodymodel/blob/aa6199ff48b524d3ce7b827b6cabe144c23688ab/mex-wholebodymodel/matlab/wrappers/wbm_setWorldLink.m . 
Do you think we can remove it @Ganimed @gabrielenava ?

**Comment by Ganimed** [comment]
I don't use the function *wbm_setWorkdLink()* in my project. I've avoided this function from begin on, since it was confusing me. If nobody else is using it, you can remove this function.

**Comment by gabrielenava** [comment]
It is also not used in the controllers, so I think we can remove it

**Comment by traversaro** [comment]
Fixed in https://github.com/robotology/mex-wholebodymodel/commit/7a0b3f130e73aff3b1e659a8059416d6c690dd4e .
