### ISSUE TITLE
ChangeLog is broken 

### ISSUE THREAD

**Issue by traversaro** [robotology/mex-wholebodymodel#88]
As already noted in https://github.com/robotology/mex-wholebodymodel/commit/13d8390d91fc5540bbd2703ae7d878cae66a37c9#commitcomment-20813414 , the changelog of each release should link at the differences between the tag of the released versions and the previous release, while in https://github.com/robotology/mex-wholebodymodel/commit/13d8390d91fc5540bbd2703ae7d878cae66a37c9#commitcomment-20813414 the release 0.2 is linked to the differences between the branch `master` and the branch `recovery`, that at this moment point at the same commit (this is exactly why you should use `tags` rather than `branches` for the changelogs.

**Comment by gabrielenava** [comment]
addressed in https://github.com/robotology/mex-wholebodymodel/commit/dcf188fc83c1c6f2a8ad7f4d9280640d9b0eee75
