### ISSUE TITLE
wholeBodyModel does not initialize when switching initialization from icub to icubGazeboSim and viceversa without restarting MATLAB.

### ISSUE THREAD

**Issue by jeljaik** [robotology/mex-wholebodymodel#9]
To be more clear, suppose you initialize wholeBodyModel as:
`wholeBodyModel('model-initialise', 'icub')` but you're not connected to the robot, then you wanna switch initialization (without restarting Matlab) to `wholeBodyModel('model-initialize', 'icubGazeboSim')` what you get is the default error message for unexisting component.

**Comment by traversaro** [comment]
The bug mentioned in the last issue was solved in https://github.com/robotology/mex-wholebodymodel/commit/9255ca6bc0326ee3fc0cb61e86e46b4487eba6b4 . 
For loading/unloading different models, we have now a working test validating that this is working (see https://github.com/robotology/mex-wholebodymodel/blob/master/tests/initialiseTest.m ), so I guess we can close the issue.
